services:
  web_api:
    container_name: carapi
    build: .
    image: carapiimage
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgres
    container_name: postgres_db
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: p@55w0rd
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  postgres_data: